trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

pr:
  autoCancel: true
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

#variables:
#  CCACHE_DIR: $(Pipeline.Workspace)/.ccache

jobs:
- job:
  displayName: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      Clang-8:
        CC: clang-8
        CXX: clang++-8
        BuildType: Debug
        SelfHost: false
        CMakeArgs: ''

      GCC-8:
        CC: gcc-8
        CXX: g++-8
        BuildType: Debug
        SelfHost: false
        CMakeArgs: ''

  steps:
#    - script: |
#        sudo apt-get install ccache ninja-build -y
#        echo "##vso[task.prependpath]/usr/lib/ccache"
#        export CCACHE_CPP2=yes
#      displayName: 'Install build dependencies'
#    - task: Cache@2
#      inputs:
#        key: 'ccache | "$(Agent.JobName)"'
#        path: $(CCACHE_DIR)
#      displayName: 'CCache'
    - script: git submodule update --init
      displayName: 'Cloning Submodules'
    - script: cmake -H. -BBuild
      displayName: 'CMake Configure'
    - script: cmake --build Build
      displayName: 'CMake Build'

- job:
  displayName: Windows
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      64-bit Debug:
        BuildType: Debug
        CMakeArgs: ''

  steps:
    - script: git submodule update --init
      displayName: 'Cloning Submodules'
    - script: cmake -H. -BBuild
      displayName: 'CMake Configure'
    - script: cmake --build Build
      displayName: 'CMake Build'

- job:
  displayName: MacOSX
  pool:
    vmImage: 'macOS-latest'

  steps:
    - script: git submodule update --init
      displayName: 'Cloning Submodules'
    - script: cmake -H. -BBuild
      displayName: 'CMake Configure'
    - script: cmake --build Build
      displayName: 'CMake Build'
